export const NAME_RESERVATION_PROCESS_ID = 101;
export const INCORPORATE_PROCESS_ID = 103;
export const CONTINUATION_PROCESS_ID = 105;
export const PQ_PROCESS_ID = 702;
export const CHANGE_PROCESS_ID = 300;
export const CERTIFICATE_OF_GOODSTANDING_PROCESS_ID = 501;
export const CERTIFICATE_OF_OFFICIAL_SEARCH_PROCESS_ID = 502;
export const ROD_PROCESS_ID = 111;
export const LETTER_OF_CONFIRMATION_PROCESS_ID = 505;
export const ANNUAL_RENEWAL = 107;
export const COMPLAINT = 804;
export const CESSATION = 407;


